### ISSUE TITLE
ArgumentError: iv must be 16 bytes

### ISSUE THREAD

**Issue by brandysnaps** [itay-grudev/encryption#1]
I have just upgraded to Ruby 2.4 and have started seeing this issue:
```
ArgumentError: iv must be 16 bytes
  /.../gems/encryption-1.1.8/lib/modules/symmetric.rb:42:in `iv='
  /.../gems/encryption-1.1.8/lib/modules/symmetric.rb:42:in `cipher_init'
  /.../gems/encryption-1.1.8/lib/modules/symmetric.rb:28:in `decrypt'
  /.../gems/encryption-1.1.8/lib/encryption.rb:15:in `method_missing'
```

I've had a look at the default value for `iv`:
```
$ cat /.../gems/encryption-1.1.8/lib/configuration/symmetric.rb
module Encryption
  module Configuration
    class Symmetric < Base

      def initialize
        super
        @config = {
          :key => nil,
          :iv => "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0",
          :cipher => 'aes-256-cbc'
        }
      end

    end
  end
```

It has a length of 24 bytes. Updating the value to 16 bytes allows me to get past the error. Is it possible to add support for >Ruby 2.3?

Thanks very much.

**Comment by itay-grudev** [comment]
I plan to discontinue this project as I no longer have time to maintain it. I'm sorry, but at this time I don't plan to fix this issue.
